<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        DB::statement('PRAGMA foreign_keys=on;');
    }

    /**
     * @param null $user
     * @return $this
     */
    protected function signIn($user = null)
    {
        $user = $user ?: create('App\User');
        $this->actingAs($user);
        return $this;
    }

    /**
     * @param null $admin
     * @return $this
     */
    protected function signInAdmin($admin = null)
    {
        $admin = $admin ?: create('App\User');
        config(['podonak.administrators' => [$admin->email]]);
        $this->actingAs($admin);
        return $this;
    }

}
